platform :ios, '11.0'
swift_version = '4.2'
use_frameworks!

target 'Gist' do
  pod 'MaterialComponents/BottomAppBar'
  pod 'MaterialComponents/BottomAppBar+ColorThemer'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Disable Code Coverage for Pods projects
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end
end

